### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by UnclePsymon** [hayden-fr/ComfyUI-Model-Manager#7]
Hi! The import fails. ComfyUI and all custom nodes are up to date. Any ideas? Thx!

```
[Maras IT] Initialization
** ComfyUI startup time: 2024-04-18 14:08:36.273054
** Platform: Linux
** Python version: 3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0]
** Python executable: /dockerx/ComfyUI/venv/bin/python
** Log path: /dockerx/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI-MarasIT-Nodes
   0.1 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 12272 MB, total RAM 32005 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6700 XT : native
VAE dtype: torch.float32
Using split optimization for cross attention
Adding extra search path checkpoints /dockerx/ComfyUI/models/checkpoints
Adding extra search path gligen /dockerx/ComfyUI/models/gligen
Adding extra search path gligen /LinuxExtra/StableDiffusionKram/models/gligen
Adding extra search path embeddings /LinuxExtra/StableDiffusionKram/embeddings
Adding extra search path upscale_models /LinuxExtra/StableDiffusionKram/models
Adding extra search path controlnet /LinuxExtra/StableDiffusionKram/models/ControlNet
Adding extra search path vae /LinuxExtra/StableDiffusionKram/models/VAE
FaceDetailer: Model directory already exists
FaceDetailer: Model already exists
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob
/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
Total VRAM 12272 MB, total RAM 32005 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6700 XT : native
VAE dtype: torch.float32
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/dockerx/ComfyUI/custom_nodes/was-node-suite-
comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

        "Believe in yourself, and the rest will fall into place." - Unknown

[Maras IT] Loaded
### Loading: ComfyUI-Inspire-Pack (V0.69.4)
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /LinuxExtra/StableDiffusionKram/custom_nodes/comf
yui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionPr
ovider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutio
nProvider']
/dockerx/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: 
Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. D
WPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to 
OpenCV with CPU device. DWPose might run very slowly")

[rgthree] Loaded 37 extraordinary nodes.
[rgthree] Will use rgthree's optimized recursive execution.

### Loading: ComfyUI-Manager (V2.19)
### ComfyUI Revision: 2134 [d64e2174] | Released on '2024-04-17'
[ComfyUI_zfkun] check start
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/ma
in/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/ma
in/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/ma
in/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/ma
in/extension-node-map.json
[ComfyUI_zfkun] "Pillow" is not installed. Trying to install.
Requirement already satisfied: Pillow in ./ComfyUI/venv/lib/python3.9/site-packages (9.5.0)
[ComfyUI_zfkun] "Pillow" is installed
[ComfyUI_zfkun] all dependency installed
[ComfyUI_zfkun] check end
[ComfyUI_zfkun] boot start
[ComfyUI_zfkun] node install: share_screen.js
[ComfyUI_zfkun] node install: preview_text_multiline.js
[ComfyUI_zfkun] node install: preview_text.js
[ComfyUI_zfkun] boot end
### Loading: ComfyUI-Impact-Pack (V4.87.6)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_contro
lnet_aux add-on)...Success!
Comfy-Easy-Use (v1.1.4): Loaded
Traceback (most recent call last):
  File "/dockerx/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/dockerx/ComfyUI/custom_nodes/ComfyUI-Model-Manager/__init__.py", line 30, in <module>
    config_loader_spec.loader.exec_module(config_loader)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/dockerx/ComfyUI/custom_nodes/ComfyUI-Model-Manager/config_loader.py", line 5, in <module>
    class Rule:
  File "/dockerx/ComfyUI/custom_nodes/ComfyUI-Model-Manager/config_loader.py", line 9, in Rule
    value_min: int | float | None
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Cannot import /dockerx/ComfyUI/custom_nodes/ComfyUI-Model-Manager module for custom nodes: unsupported
 operand type(s) for |: 'type' and 'type'
Workspace manager - Openning file hash dict
### Loading: Workspace Manager (V1.0.0)

Import times for custom nodes:
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/comfyui-floodgate
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/cd-tuner_negpip-ComfyUI
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/comfyui-tooling-nodes
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI_TiledKSampler
   0.0 seconds (IMPORT FAILED): /dockerx/ComfyUI/custom_nodes/ComfyUI-Model-Manager
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/comfyui-inpaint-nodes
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI-MarasIT-Nodes
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI_ELLA
   0.1 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.1 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.1 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI-Manager
   0.2 seconds: /dockerx/ComfyUI/custom_nodes/ymc-node-suite-comfyui
   0.7 seconds: /dockerx/ComfyUI/custom_nodes/facedetailer
   0.7 seconds: /dockerx/ComfyUI/custom_nodes/was-node-suite-comfyui
   2.0 seconds: /dockerx/ComfyUI/custom_nodes/ComfyUI_zfkun

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by cdb-boop** [comment]
My bad. I was using using unions and forgot to remove them. I've opened a PR #8.
